using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DataAccessLayer;
using BussinessLogicLayer;

namespace FitnessCenter
{
    public partial class ExpireMember : DevExpress.XtraEditors.XtraForm
    {
        public int Id;
        public bool isAdd = true;
        public ExpireMember()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void btnClose_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void btnHuy_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void btnTao_Click(object sender, EventArgs e)
        {
            int rowIndex = gvDanhMuc.FocusedRowHandle;
            string colID = "Customer_ID";
            object value = gvDanhMuc.GetRowCellValue(rowIndex, colID);
            if (value != null)
            {
                MemberDetail md = new MemberDetail();
                md.Id = (int)value;
                md.isAdd = false;
                md.ShowDialog();
                sqlDataSource1.Fill();
            }
            else
            {
                XtraMessageBox.Show("Bạn chưa chọn đối tượng để cập nhật", "Fitness Center", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
        }

        private void ExpireMember_Load(object sender, EventArgs e)
        {
            DateTime date = DateTime.Now;
            String filter = "[Customer_EndDate] <='" + date + "'";
            gvDanhMuc.ActiveFilterString = filter;
        }
    }
}