using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DataAccessLayer;
using BussinessLogicLayer;
using System.Text.RegularExpressions;

namespace FitnessCenter
{
    public partial class ExpireMemberDetail : DevExpress.XtraEditors.XtraForm
    {
        public int Id;
        public ExpireMemberDetail()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void btnClose_Click(object sender, EventArgs e)
        {
            this.Close();
        }
        private void btnHuy_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void btnTao_Click(object sender, EventArgs e)
        {
            try
            {
                if (lkeLoaiThe.Text == "Chọn thẻ")
                {
                    lbTrangThai.Text = "*Vui lòng chọn loại thẻ";
                    lkeLoaiThe.Focus();
                }
                else
                {
                    if (dtNgayBatDau.DateTime > dtNgayKetThuc.DateTime)
                    {
                        lbTrangThai.Text = "*Khoảng thời gian không hợp lệ";
                        dtNgayKetThuc.Focus();
                    }
                    else
                    {
                        string group = lkeLoaiThe.GetColumnValue("Membership_ID").ToString();
                        int memberId = Convert.ToInt32(group);
                        DateTime beginDate = dtNgayBatDau.DateTime;
                        DateTime endDate = dtNgayKetThuc.DateTime;
                        int totalAmount = 0;
                        string notePayment = "";
                        BLL_Human.UpdateCustomerExpire(Id, memberId, beginDate, endDate);
                        int lastID = BLL_Human.GetLastIdCustomer();
                        BLL_Payment.InsertPayment(lastID, beginDate, endDate, totalAmount, notePayment);
                        this.Close();
                    }
                }
            }
            catch (Exception ex)
            {
                String info = ex.Message;
                MessageError error = new MessageError();
                error.message = info;
                error.ShowDialog();
            }
        }

        private void FillData()
        {

            if (Id != 0)
            {
                DataFitnessCenterDataContext db = new DataFitnessCenterDataContext();
                var customer = db.Customers.Where(i => i.Customer_ID == (int)Id).SingleOrDefault();
                if (customer != null)
                {
                    lbHoTen.Text = customer.Customer_Name;
                    lbNgaySinh.Text = Convert.ToString(customer.Customer_Age);
                    lbGioiTinh.Text = customer.Customer_Sex;
                    dtNgayBatDau.EditValue = customer.Customer_StartDate;
                    dtNgayKetThuc.EditValue = customer.Customer_EndDate;
                    lkeLoaiThe.EditValue = customer.Membership_ID;
                }
            }
        }


        private void MemberExpire_Load(object sender, EventArgs e)
        {
            FillData();
        }
    }
}