using BussinessLogicLayer;
using DataAccessLayer;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace FitnessCenter
{
    public partial class SettingManagement : Form
    {
        public int Id;
        public bool isAdd = true;
        public SettingManagement()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
        }

        private void SettingManagement_Load(object sender, EventArgs e)
        {
            FillDataUpdate();
            FillData();
            txtMa.ReadOnly = true;
        }
        private void Reset()
        {
            txtGhiChu.Text = "";
            txtTenThe.Text = "";
            txtGiaTien.Text = "";
        }

        private void btnLamMoi_Click(object sender, EventArgs e)
        {
            Reset();
            sqlDataSource2.Fill();
        }
        private void FillDataUpdate()
        {
            if (Id != 0)
            {
                DataFitnessCenterDataContext db = new DataFitnessCenterDataContext();
                var membership = db.Memberships.Where(i => i.Membership_ID == Id).SingleOrDefault();
                if (membership != null)
                {
                    txtTenThe.EditValue = membership.Membership_Name;
                    txtGiaTien.EditValue = membership.Membership_Price;
                    txtGhiChu.Text = membership.Membership_Note;
                    txtMa.ReadOnly = true;
                }
            }
        }
        private void FillData()
        {
            DataFitnessCenterDataContext db = new DataFitnessCenterDataContext();
            var fitness = db.FitnessCenters.Where(i => i.FitnessCenter_ID == 1).SingleOrDefault();
            if (fitness != null)
            {
                txtTenPhong.EditValue = fitness.FitnessCenter_Name;
                lbTieuDe.Text = fitness.FitnessCenter_Name;
                txtDiaChi.EditValue = fitness.FitnessCenter_Address;
                txtDienThoai.Text = fitness.FitnessCenter_Tel;
                txtEmail.Text = fitness.FitnessCenter_Email;
                txtFacebook.Text = fitness.FitnessCenter_Facebook;
                lbTenPhong.Text = fitness.FitnessCenter_Name;
                lbDiaChi.Text = fitness.FitnessCenter_Address;
                lbSoDienThoai.Text = fitness.FitnessCenter_Tel;
                lbEmail.Text = fitness.FitnessCenter_Email;
                lbFacebook.Text = fitness.FitnessCenter_Facebook;
            }
        }

        private void SaveUpdate()
        {
            try
            {

                if (string.IsNullOrEmpty(txtTenThe.Text))
                {
                    lbTrangThai.Text = "*Vui lòng nhập tên thẻ";
                    txtTenThe.Focus();
                }
                else
                {
                    if (txtGiaTien.Value == 0)
                    {
                        lbTrangThai.Text = "*Vui lòng nhập giá tiền";
                        txtGiaTien.Focus();
                    }
                    else
                    {
                        string name = txtTenThe.Text;
                        string note = txtGhiChu.Text;
                        int price = Convert.ToInt32(txtGiaTien.Value.ToString());
                        BLL_Membership.UpdateMembership(Id, name, price, note);
                        Reset();
                        sqlDataSource2.Fill();
                        lbTrangThai.Text = "";
                    }
                }

            }
            catch (Exception ex)
            {
                String info = ex.Message;
                MessageError error = new MessageError();
                error.message = info; 
                error.ShowDialog();
            }
        }

        private void btnThem_Click(object sender, EventArgs e)
        {
            try
            {
                if (isAdd == false)
                {
                    SaveUpdate();
                }
                else
                {
                    if (string.IsNullOrEmpty(txtTenThe.Text))
                    {
                        lbTrangThai.Text = "*Vui lòng nhập tên thẻ";
                        txtTenThe.Focus();
                    }
                    else
                    {
                        if (txtGiaTien.Value == 0)
                        {
                            lbTrangThai.Text = "*Vui lòng nhập giá tiền";
                            txtGiaTien.Focus();
                        }
                        else
                        {
                            string name = txtTenThe.Text;
                            string note = txtGhiChu.Text;
                            int price = Convert.ToInt32(txtGiaTien.Value.ToString());
                            BLL_Membership.InsertMembership(name, price, note);
                            Reset();
                            sqlDataSource2.Fill();
                            lbTrangThai.Text = "";
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                String info = ex.Message;
                MessageError error = new MessageError();
                error.message = info;
                error.ShowDialog();
            }
        }

        private void csmCapNhat_Click(object sender, EventArgs e)
        {
            int rowIndex = gvDanhMuc.FocusedRowHandle;
            string colID = "Membership_ID";
            object value = gvDanhMuc.GetRowCellValue(rowIndex, colID);
            if (value != null)
            {
                Id = (int)value;
                isAdd = false;
                FillDataUpdate();
                sqlDataSource2.Fill();
            }
            else
            {
                XtraMessageBox.Show("Bạn chưa chọn đối tượng để cập nhật", "Fitness Center", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
        }

        private void csmXoa_Click(object sender, EventArgs e)
        {
            try
            {
                if (XtraMessageBox.Show("Bạn có muốn xóa không?", "Fitness Center", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                {
                    int rowIndex = gvDanhMuc.FocusedRowHandle;
                    string colID = "Membership_ID";
                    object value = gvDanhMuc.GetRowCellValue(rowIndex, colID);
                    if (value != null)
                    {
                        DataFitnessCenterDataContext dc = new DataFitnessCenterDataContext();
                        var ing = dc.Memberships.Where(s => s.Membership_ID == (int)value).SingleOrDefault();
                        if (ing != null)
                        {
                            dc.Memberships.DeleteOnSubmit(ing);
                            dc.SubmitChanges();
                            sqlDataSource2.Fill();
                        }
                    }
                    else
                    {
                        XtraMessageBox.Show("Bạn chưa chọn đối tượng cần xóa", "Fitness Center", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    }
                }
            }
            catch (Exception)
            {

                XtraMessageBox.Show("Không được phép xóa đối tượng này, đối tượng đã được thêm ở một danh mục khác", "Fitness Center", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }



        private void btnLuu_Click(object sender, EventArgs e)
        {
            try
            {
                if (string.IsNullOrEmpty(txtTenPhong.Text))
                {
                    lbTrangThai.Text = "*Vui lòng nhập tên phòng";
                    txtTenPhong.Focus();
                }
                else
                {
                    if (string.IsNullOrEmpty(txtDienThoai.Text))
                    {
                        lbTrangThai.Text = "*Vui lòng nhập số điện thoại";
                        txtDienThoai.Focus();
                    }
                    else
                    {
                        if (string.IsNullOrEmpty(txtDiaChi.Text))
                        {
                            lbTrangThai.Text = "*Vui lòng nhập địa chỉ";
                            txtDiaChi.Focus();
                        }
                        else
                        {
                            string name = txtTenPhong.Text;
                            string address = txtDiaChi.Text;
                            string tel = txtDienThoai.Text;
                            string email = txtEmail.Text;
                            string facebook = txtFacebook.Text;
                            lbTieuDe.Text = name;
                            lbTenPhong.Text = name;
                            lbDiaChi.Text = address;
                            lbEmail.Text = email;
                            lbSoDienThoai.Text = tel;
                            lbFacebook.Text = facebook;
                            BLL_Fitness.UpdateFitnessCenter(name, tel, email, address, facebook);
                            lbTrangThai.Text = "";
                        }
                    }
                }

            }
            catch (Exception ex)
            {
                String info = ex.Message;
                MessageError error = new MessageError();
                error.message = info;
                error.ShowDialog();
            }
        }

        private void txtDienThoai_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (!Char.IsDigit(e.KeyChar) && !Char.IsControl(e.KeyChar))
                e.Handled = true;
        }

        private void txtDienThoai_Validating(object sender, CancelEventArgs e)
        {
            if (txtDienThoai.Text.Length < 10 || txtDienThoai.Text.Length > 11)
            {

                lbTrangThai.Text = "*Số điện thoại phải từ 10 đến 11 số";
                txtDienThoai.Focus();
                e.Cancel = true;
                btnLuu.Enabled = false;
            }
            else
            {
                lbTrangThai.Text = "";
                e.Cancel = false;
                btnLuu.Enabled = true;
            }
        }

        private void txtEmail_Validating(object sender, CancelEventArgs e)
        {
            string email = txtEmail.Text;
            Regex regex = new Regex(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$");
            Match match = regex.Match(email);
            if (!match.Success)
            {
                lbTrangThai.Text = "*Địa chỉ email không hợp lệ";
                e.Cancel = true;
                btnLuu.Enabled = false;
            }
            else
            {
                lbTrangThai.Text = "";
                e.Cancel = false;
                btnLuu.Enabled = true;
            }
        }
    }

}
